### ISSUE TITLE
Anyway to do volume up or volume down?

### ISSUE THREAD

**Issue by linkx2252** [NorthernMan54/homebridge-cmd-television#10]

**Comment by NorthernMan54** [comment]
Sorry volume is not supported.  If you want to add it, I would gladly accept a pull request with the feature.

**Comment by linkx2252** [comment]
Unfortunately, I am dumb as rocks and can barely implement let alone
contribute. Thanks for the fast response.

**Comment by UKenGB** [comment]
Worth pointing out perhaps that the Apple TV has no concept of volume, so hard to know how such a thing could be implemented.
