### ISSUE TITLE
Question: Adding a second, third ATV

### ISSUE THREAD

**Issue by MatGriffin** [NorthernMan54/homebridge-cmd-television#13]
Great plugin, working flawlessly with 1 ATV but how do I set up for a second ATV?

**Comment by A-vesalius** [comment]
Do install steps 1-7 for each appletv, but change the name of the fle stored to something different for each atv in steps 5&6. for example ~/.homebridge/atv2_airplay.cred or ~/.homebridge/masteratv_AirPlay.cred. 

follow the example configuration `"accessories": [ `  to add a complete new accessory for each of your atv's but reference the appropriate corresponding saved files for each, for example `cat ~/.homebridge/atv2_airplay.cred` --companion-credentials `cat ~/.homebridge/atv2_companion.cred`

**Comment by MatGriffin** [comment]
Great, thank you :)
