### ISSUE TITLE
Question: Homebridge Docker

### ISSUE THREAD

**Issue by mcarame** [NorthernMan54/homebridge-cmd-television#2]
Hi @NorthernMan54,
thank you for this plug-in. Really appreciated!

There is any chance in the future to get **homebridge-cmd-television** available via [oznu/docker-homebridge](https://github.com/oznu/docker-homebridge) like your **homebridge-alexa** plug-in?

Thanks in advance.

**Comment by NorthernMan54** [comment]
Can you elaborate on this request further?

I’m not a docker user, so don’t really understand the question or issue.

**Comment by mcarame** [comment]
I mean, without run any command in terminal or install dependencies.
When I install a plug-in from the Homebridge UI I just need to type the name in the search field and click install, nothing else.

**Comment by NorthernMan54** [comment]
Great suggestion

The one piece I’m not sure of is the ability to install the pyatv package as part of the install.
